spring:
  datasource:
    url: jdbc:h2:file:./db/song;DATABASE_TO_LOWER=TRUE;
    username: user
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update